version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env.prod
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 2s
      retries: 20
    networks:
      - nestjs_network

  nexus-tag-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nexus-tag-server
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
